### ISSUE TITLE
Killed error when converting,  without error description

### ISSUE THREAD

**Issue by stevelizcano** [hukkelas/DeepPrivacy#6] opened 2019-09-21 09:25 UTC
When running the program and doing a conversion (after downloading the model and setting up all dependencies),  I keep getting a Killed error about what seems to be half way through the process:

```
(base) stephenlizcano@deepfacelab-vm:~/DeepPrivacy$ python -m deep_privacy.inference.anonymize_video models/isvc_large/config.yml --source_path /home/stephenlizcano/deepfakeResize.mp4 --target_path /home/stephenlizcano/video_anonymized.mp4
CONFIG USED:
================================================================================
logging.num_ims_per_log                            500
logging.num_ims_per_save_image                     100000
logging.num_ims_per_checkpoint                     200000
max_imsize                                         128
use_full_validation                                False
load_fraction_of_dataset                           False
dataset                                            yfcc100m128
train_config.transition_iters                      1200000
train_config.learning_rate                         0.00175
train_config.amp_opt_level                         O1
train_config.batch_size_schedule                   {4: 256, 8: 256, 16: 256, 32: 128, 64: 96, 128: 64}
models.start_channel_size                          512
models.pose_size                                   14
models.image_channels                              3
models.generator.running_average_decay             0.999
models.discriminator.structure                     normal
config_path                                        models/isvc_large/config.yml
checkpoint_dir                                     models/isvc_large/checkpoints
generated_data_dir                                 models/isvc_large/generated_data
summaries_dir                                      models/isvc_large/summaries
source_path                                        /home/stephenlizcano/deepfakeResize.mp4
target_path                                        /home/stephenlizcano/video_anonymized.mp4
anonymize_source                                   False
max_face_size                                      1.0
without_source                                     False
================================================================================
 [*] Loading checkpoint from models/isvc_large/checkpoints/step_40000000.ckpt succeed!
extending G 512
extending G 512
extending G 512
extending G 256
extending G 128
Anonymizer initialized. Keypoint threshold: 0.1Face threshold: 0.6
================================================================================
Anonymizing video.
Duration: 90.38. Total frames: 2259, FPS: 25.0
Anonymizing from: 0(0.0), to: 2259(90.36)
Reading frames: 100%|███████████████████████| 2259/2259 [00:30<00:00, 72.91it/s]
Batch detecting faces:   0%|                           | 0/2259 [00:00<?, ?it/s]Finished loading DSFD model!
Batch detecting faces: 100%|████████████████| 2259/2259 [10:02<00:00,  3.79it/s]
Killed
```

**Comment by hukkelas** [comment] 2019-09-23 07:06
What GPU model are you using? I believe this could be the GPU running out of VRAM.
In [line 10](https://github.com/hukkelas/DeepPrivacy/blob/ce386a40e5791d7ffa37b991897f3bf451b07b22/deep_privacy/inference/anonymize_video.py#L10) in `anonymize_video`, you can set the required batch size of the generator. 

Can you try changing `32` to a lower value, such as `4`, `8` or `16`. Depending on your GPU. We set `32` as the batch size as we were using a V100 with  32GB of VRAM.

**Comment by stevelizcano** [comment] 2019-09-23 22:38
Thanks! We're using a V100 with 16GB VRAM, and tried the settings in `anonymize_video` with 16, 8, and 4, with no luck. :/

**Comment by hukkelas** [comment] 2019-09-24 06:23
Hmmm, ok. Could you send me information about your environment? OS version, python version, and the output of pip list?

**Comment by hukkelas** [comment] 2019-09-24 13:40
Your environment looks fine, you can also test out our docker container `docker pull haakohu/deep_privacy` with nvidia-docker.

I believe there is some system resources going out, such as RAM. We are caching both the anonymized video and the original video in memory, so depending on the resolution and length of the video, it might not work. Are you able to run our system with a single image?

If so, you might want to track the memory usage during inference on the video. My guess is that it is able to pre-process all the faces, however during [this allocation](https://github.com/hukkelas/DeepPrivacy/blob/ce386a40e5791d7ffa37b991897f3bf451b07b22/deep_privacy/inference/deep_privacy_anonymizer.py#L81)  it runs out of memory. Could you maybe add simple print before/after this call, to assert if this is where the problem is.

**Comment by stevelizcano** [comment] 2019-09-24 19:14
From the root DeepPrivacy folder, or the ./deep_privacy one, i cannot seem to figure out how to run nvidia-docker successfully. Here's what I'm using:

```
nvidia-docker run --rm -it -v $PWD:/app -e CUDA_VISIBLE_DEVICES=1 deep_privacy python -m deep_privacy.inference.anonymize_video models/isvc_large/config.yml --source_path /home/stephenlizcano/deepfakeResize.mp4 --target_path /home/stephenlizcano/video_anonymized.mp4
```

**Comment by hukkelas** [comment] 2019-09-25 09:07
Oh, I believe the command in readme.md was a bit outdated, updated it now! Try:
```
nvidia-docker run --rm  -it -v $PWD:/workspace  -e CUDA_VISIBLE_DEVICES=0 deep_privacy python -m deep_privacy.inference.anonymize_video models/isvc_large/config.yml --source_path /home/stephenlizcano/deepfakeResize.mp4 --target_path /home/stephenlizcano/video_anonymized.mp4

```
Set CUDA_VISIBLE_DEVICES=0 if you have a single GPU machine (This is how to set what GPU you want the model to use)

**Comment by hukkelas** [comment] 2019-10-01 08:02
I'm closing this for now, reopen this issue if your issue still persists :)

**Closed by hukkelas** 2019-10-01 08:02 UTC
